# Generated by Django 4.1 on 2024-11-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Delivery_Person",
            fields=[
                ("del_id", models.AutoField(primary_key=True, serialize=False)),
                ("del_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=50)),
                ("mobile_number", models.BigIntegerField(unique=True)),
                ("address", models.CharField(max_length=300)),
                ("working_for", models.CharField(max_length=100)),
            ],
        ),
    ]
