# Generated by Django 4.1 on 2024-11-21 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Delivery", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delivery_person",
            name="working_for",
            field=models.CharField(default="", max_length=100),
        ),
    ]
