# Generated by Django 5.1.2 on 2024-11-24 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0002_alter_delivery_person_working_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_person',
            name='working_for',
            field=models.BigIntegerField(),
        ),
    ]
