# Generated by Django 4.1 on 2024-11-08 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Customer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                ("feed_id", models.AutoField(primary_key=True, serialize=False)),
                ("res_name", models.CharField(max_length=100)),
                ("rating", models.IntegerField(max_length=2)),
                ("cust_feedback", models.CharField(max_length=200)),
                ("cust_feedback_by", models.EmailField(max_length=254, unique=True)),
                ("admin_feedback", models.CharField(max_length=200)),
                ("admin_feedback_by", models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
