# Generated by Django 4.1 on 2024-11-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Customer", "0002_feedback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="admin_feedback_by",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="cust_feedback_by",
            field=models.EmailField(max_length=254),
        ),
    ]
