# Generated by Django 4.1 on 2024-11-09 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Customer", "0003_alter_feedback_admin_feedback_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback", name="rating", field=models.IntegerField(),
        ),
    ]
