# Generated by Django 5.1.2 on 2024-11-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0005_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cust_email',
            field=models.EmailField(default=' ', max_length=254),
        ),
    ]
