# Generated by Django 4.1 on 2024-11-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Customer", "0006_cart_cust_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart", name="res_id", field=models.IntegerField(default=0),
        ),
    ]
