# Generated by Django 5.1.2 on 2024-11-08 08:01

import Restaurant.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_picture',
            field=models.ImageField(default='static/res_home.jpg', upload_to='res_picture/', validators=[Restaurant.models.validate_image]),
        ),
    ]
