# Generated by Django 4.1 on 2024-11-19 20:46

import Restaurant.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Restaurant", "0002_restaurant_restaurant_picture"),
    ]

    operations = [
        migrations.CreateModel(
            name="Food",
            fields=[
                ("food_id", models.AutoField(primary_key=True, serialize=False)),
                ("food_name", models.CharField(max_length=100)),
                ("food_description", models.CharField(max_length=300)),
                ("food_price", models.IntegerField()),
                (
                    "food_picture",
                    models.ImageField(
                        upload_to="foods/",
                        validators=[Restaurant.models.validate_image],
                    ),
                ),
                ("food_by", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="restaurant_picture",
            field=models.ImageField(
                default="res_picture/res_home.jpg",
                upload_to="res_picture/",
                validators=[Restaurant.models.validate_image],
            ),
        ),
    ]
