# Generated by Django 5.1.2 on 2024-11-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0003_food_alter_restaurant_restaurant_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('cust_email', models.EmailField(max_length=254)),
                ('cust_name', models.CharField(max_length=100)),
                ('cust_address', models.CharField(max_length=300)),
                ('order_details', models.CharField(max_length=2000)),
                ('total_price', models.IntegerField()),
                ('res_id', models.BigIntegerField()),
                ('del_id', models.BigIntegerField()),
                ('order_status', models.CharField(default='Pending', max_length=15)),
                ('ordered_on', models.DateTimeField()),
            ],
        ),
    ]
